"""Command line entry point: ``env-contract check`` and ``env-contract template``."""

import argparse
import json
import os
import sys
from dataclasses import dataclass

from env_contract import __version__, compose, env_template, python_source, safe_io
from env_contract.errors import ParseError

EXIT_OK = 0
EXIT_DRIFT = 1
EXIT_ERROR = 2


@dataclass
class Contract:
    code: set[str]  # A
    template: set[str]  # B
    compose: set[str] | None  # C, None when there is no compose file
    warnings: list[str]


def collect(project: str) -> Contract:
    scan = python_source.scan_project(project)
    warnings = list(scan.warnings)

    template, template_warnings = env_template.read_template_keys(project)
    if template is None:
        warnings.append(f"{safe_io.TEMPLATE_NAME}: not found")
    warnings.extend(template_warnings)

    compose_names, compose_warnings = compose.read_compose_names(project)
    if compose_names is None:
        warnings.append(f"no compose file found (looked for {', '.join(compose.COMPOSE_FILES)})")
    warnings.extend(compose_warnings)

    return Contract(scan.names, template or set(), compose_names, warnings)


def diff(contract: Contract) -> dict:
    a, b, c = contract.code, contract.template, contract.compose
    return {
        "missing_in_template": sorted((a | (c or set())) - b),
        "unused_in_code": sorted(b - a),
        "undeclared_in_compose": None if c is None else sorted((a | b) - c),
        "warnings": contract.warnings,
    }


def _has_drift(report: dict) -> bool:
    return bool(
        report["missing_in_template"]
        or report["unused_in_code"]
        or report["undeclared_in_compose"]
    )


def _print_text(report: dict) -> None:
    labels = {
        "missing_in_template": "used in code or compose but missing from .env.example",
        "unused_in_code": "in .env.example but never read by code",
        "undeclared_in_compose": "used in code or .env.example but not wired into compose",
    }
    for key, label in labels.items():
        names = report[key]
        if names is None:
            print(f"{key}: skipped (no compose file)")
            continue
        print(f"{key}: {len(names)} ({label})")
        for name in names:
            print(f"  {name}")
    for warning in report["warnings"]:
        print(f"warning: {warning}")


def cmd_check(args: argparse.Namespace) -> int:
    report = diff(collect(args.project))
    if args.json:
        print(json.dumps(report, indent=2))
    else:
        _print_text(report)
    return EXIT_DRIFT if _has_drift(report) else EXIT_OK


def cmd_template(args: argparse.Namespace) -> int:
    contract = collect(args.project)
    names = contract.code | contract.template | (contract.compose or set())
    project_name = os.path.basename(os.path.abspath(args.project))
    print(f"# Environment variables for {project_name} (generated by env-contract; values left blank)")
    for name in sorted(names):
        print(f"{name}=")
    for warning in contract.warnings:
        print(f"warning: {warning}", file=sys.stderr)
    return EXIT_OK


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="env-contract",
        description="Diff the environment variables a Python project reads, documents and wires into Compose.",
    )
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")
    sub = parser.add_subparsers(dest="command", required=True)

    check = sub.add_parser("check", help="report drift between code, .env.example and compose")
    check.add_argument("project", help="project root directory")
    check.add_argument("--json", action="store_true", help="print the report as JSON")
    check.set_defaults(func=cmd_check)

    template = sub.add_parser("template", help="print a .env.example skeleton with every known name")
    template.add_argument("project", help="project root directory")
    template.set_defaults(func=cmd_template)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    try:
        args = parser.parse_args(argv)
    except SystemExit as exc:  # argparse reports usage errors with exit code 2
        return int(exc.code or 0)
    if not os.path.isdir(args.project):
        print(f"env-contract: error: not a directory: {args.project}", file=sys.stderr)
        return EXIT_ERROR
    try:
        return args.func(args)
    except (ParseError, safe_io.ForbiddenFileError) as exc:
        print(f"env-contract: error: {exc}", file=sys.stderr)
        return EXIT_ERROR
